version: '3.9'

services:
  nxtreserv:
    container_name: "nxtreserv"
    build: .
    volumes:
      - .:/app
    command: /bin/sh -c "/run.sh"
    ports:
      - "8000:8000"
    env_file:
      - .envs/.django
    depends_on:
      - pgdb

  pgdb:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nxtreserv
    volumes:
      - postgres_data:/var/lib/postgresql/data/



volumes:
  postgres_data:
