# Generated by Django 4.1.7 on 2023-09-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["id"]},
        ),
    ]
