# Generated by Django 4.1.7 on 2023-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_alter_room_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
